/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProgresoRouteImport } from './routes/progreso'
import { Route as PerfilesRouteImport } from './routes/perfiles'
import { Route as EmergenciaRouteImport } from './routes/emergencia'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosSlugRouteImport } from './routes/videos_.$slug'
import { Route as BibliotecaSlugRouteImport } from './routes/biblioteca_.$slug'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgresoRoute = ProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilesRoute = PerfilesRouteImport.update({
  id: '/perfiles',
  path: '/perfiles',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciaRoute = EmergenciaRouteImport.update({
  id: '/emergencia',
  path: '/emergencia',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos_/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaSlugRoute = BibliotecaSlugRouteImport.update({
  id: '/biblioteca_/$slug',
  path: '/biblioteca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/emergencia': typeof EmergenciaRoute
  '/perfiles': typeof PerfilesRoute
  '/progreso': typeof ProgresoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/emergencia': typeof EmergenciaRoute
  '/perfiles': typeof PerfilesRoute
  '/progreso': typeof ProgresoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/biblioteca/$slug': typeof BibliotecaSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof BibliotecaRoute
  '/emergencia': typeof EmergenciaRoute
  '/perfiles': typeof PerfilesRoute
  '/progreso': typeof ProgresoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videos': typeof VideosRoute
  '/biblioteca_/$slug': typeof BibliotecaSlugRoute
  '/videos_/$slug': typeof VideosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/emergencia'
    | '/perfiles'
    | '/progreso'
    | '/reset-password'
    | '/videos'
    | '/biblioteca/$slug'
    | '/videos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/emergencia'
    | '/perfiles'
    | '/progreso'
    | '/reset-password'
    | '/videos'
    | '/biblioteca/$slug'
    | '/videos/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/emergencia'
    | '/perfiles'
    | '/progreso'
    | '/reset-password'
    | '/videos'
    | '/biblioteca_/$slug'
    | '/videos_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BibliotecaRoute: typeof BibliotecaRoute
  EmergenciaRoute: typeof EmergenciaRoute
  PerfilesRoute: typeof PerfilesRoute
  ProgresoRoute: typeof ProgresoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VideosRoute: typeof VideosRoute
  BibliotecaSlugRoute: typeof BibliotecaSlugRoute
  VideosSlugRoute: typeof VideosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progreso': {
      id: '/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof ProgresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfiles': {
      id: '/perfiles'
      path: '/perfiles'
      fullPath: '/perfiles'
      preLoaderRoute: typeof PerfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencia': {
      id: '/emergencia'
      path: '/emergencia'
      fullPath: '/emergencia'
      preLoaderRoute: typeof EmergenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos_/$slug': {
      id: '/videos_/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca_/$slug': {
      id: '/biblioteca_/$slug'
      path: '/biblioteca/$slug'
      fullPath: '/biblioteca/$slug'
      preLoaderRoute: typeof BibliotecaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BibliotecaRoute: BibliotecaRoute,
  EmergenciaRoute: EmergenciaRoute,
  PerfilesRoute: PerfilesRoute,
  ProgresoRoute: ProgresoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VideosRoute: VideosRoute,
  BibliotecaSlugRoute: BibliotecaSlugRoute,
  VideosSlugRoute: VideosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
